---
all:
  hosts:
    csr1.njrusmc.net:
    # csr2.njrusmc.net:
  vars:
    ansible_network_os: "ios"
    ansible_user: "ansible"
    ansible_ssh_pass: "ansible"
    ntp_server1: "192.0.2.1"
    ntp_server2: "192.0.2.2"
...
