---
# The "all" group is at the top of the hierarchy and encompasses
# all other hosts and subgroups. This particular inventory is
# simplified and contains no subgroups.
all:
  hosts:
    # The list of hosts contained in the "all" group. These
    # can be real DNS hostnames, local host mappings, or IP
    # addresses.
    csr1.njrusmc.net:
    csr2.njrusmc.net:
  vars:
    # These are group-level variables associated with the "all"
    # group. Ansible gives many options with respect to variable
    # playment, but for a simple example playbook, embedding them in
    # the inventory file is acceptable. The "ansible_*" variables
    # serve as input for the "network_cli" transport method
    # which allow Ansible to connect to our routers. The "ntp_*"
    # variables are user-defined and represent that NTP servers we
    # are configuring in our main playbook.
    ansible_network_os: "ios"
    ansible_user: "ansible"
    ansible_password: "ansible"
    ansible_python_interpreter: "/usr/bin/env python"
    ntp_server1: "192.0.2.1"
    ntp_server2: "192.0.2.2"
...
